// <copyright file="Code.cs" company="Soli Deo Gloria Apps">
// Copyright (c) Soli Deo Gloria Apps. All rights reserved.
// </copyright>

namespace SmallC.Cc4;

/// <summary>
/// Code generated by <see cref="BackEnd.OutCodeAsync(Cc.PCode, int)"/>.
/// </summary>
/// <param name="Property">
/// Contains flag bits indicating:
/// <list type="bullet">
/// <item>The value in ax is needed (010) or zapped (020)</item>
/// <item>The value in bx is needed (010) or zapped (020)</item>
/// </list>
/// </param>
/// <param name="Text">Assembly code text.</param>
public record class Code(
    byte Property,
    string Text)
{
    /// <summary>
    /// Helper factory method to convert octal string representation.
    /// </summary>
    /// <param name="property">
    /// <see cref="Property"/> represented as an octal string.
    /// </param>
    /// <param name="text">Assembly code text.</param>
    /// <returns>
    /// New <see cref="Code"/> with <paramref name="property"/> properly
    /// converted to byte equivalent of octal string representation
    /// <paramref name="property"/>.
    /// </returns>
    public static Code Build(string property, string text)
    {
        return new(Convert.ToByte(property, 8), text);
    }
}
